In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("housing.csv")
df = df.dropna()

In [3]:
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
cat_labels, num_labels=[],[]

In [5]:
dtype_ser = df.dtypes
dtype_inx = dtype_ser.index
for i in range(len(dtype_ser)):
    if(dtype_ser.iloc[i] in ["object"]):
        cat_labels.append(dtype_inx[i])
    else:
        num_labels.append(dtype_inx[i])

In [6]:
cat_labels, num_labels

(['ocean_proximity'],
 ['longitude',
  'latitude',
  'housing_median_age',
  'total_rooms',
  'total_bedrooms',
  'population',
  'households',
  'median_income',
  'median_house_value'])

In [7]:
from sklearn.preprocessing import LabelEncoder

enc_dict = dict()
for i in cat_labels:
    enc = LabelEncoder()
    enc.fit(df[i])
    # enc_dict[i] = enc
    df[i] = enc.transform(df[i])
    # print(x_train[i])
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,3
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,1
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,1
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,1
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,1
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,1

In [8]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
df[num_labels] = scalar.fit_transform(df[num_labels])

In [9]:
x = df.drop("median_house_value", axis=1)
y = df[["median_house_value"]]

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [11]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((15324, 9), (15324, 1), (5109, 9), (5109, 1))

In [134]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

pred = model.predict(x_test)

In [135]:
pred, y_test

(array([[-0.07405729],
        [-0.64397012],
        [ 1.25050507],
        ...,
        [-0.72387718],
        [-0.40232478],
        [ 0.82697412]], shape=(5109, 1)),
        median_house_value
 253             -1.022797
 9069            -0.986413
 20210            1.710394
 6483            -0.274310
 5475             1.030344
 ...                   ...
 7328            -0.334952
 15331           -0.385197
 10891           -0.425914
 15739           -0.795826
 5519             1.204472

 [5109 rows x 1 columns])

In [136]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test, pred)

0.44760577101515364

In [137]:
df = pd.read_csv("housing.csv")
df = df.dropna()
from sklearn.model_selection import train_test_split
x, y = df.drop(["ocean_proximity"], axis=1), df["ocean_proximity"]
x_train, x_test, y_train, y_test = train_test_split(x, y)
# from sklearn.linear_model import LogisticRegression
# m = LogisticRegression()
# m.fit(df)

In [138]:
from sklearn.linear_model import LogisticRegression
m = LogisticRegression()
m.fit(x_train, y_train)

C:\Users\Vigna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [139]:
pred = m.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.5044039929536113

In [ ]:
df = pd.read_csv("housing.csv")
df = df.dropna()
from sklearn.model_selection import train_test_split
x, y = df.drop(["ocean_proximity"], axis=1), df["ocean_proximity"]
x_train, x_test, y_train, y_test = train_test_split(x, y)
from sklearn.ensemble import RandomForestClassifier
m = RandomForestClassifier()
m.fit(x_train, y_train)
pred = m.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9737717752984929

In [141]:
from sklearn.model_selection import GridSearchCV

params = {
    # "ccp_alpha":["l2", "l1"],
    'max_depth': [10, 50, 100]
}
grid = GridSearchCV(RandomForestClassifier(), params, cv=5)
grid.fit(x_train, y_train)

accuracy_score(y_test, grid.best_estimator_.predict(x_test))

0.9702485809356038

In [142]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, grid.best_estimator_.predict(x_test))

array([[2184,   24,    4,   25],
       [  34, 1623,    1,    0],
       [   1,    1,  541,    1],
       [  49,    1,   11,  609]])

In [143]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train, y_train)
accuracy_score(y_test, model.predict(x_test))

0.6073595615580348

In [144]:
type(y_train)

pandas.core.series.Series

In [146]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)
model.fit(x_train, y_train)
accuracy_score(y_test, model.predict(x_test))

0.6014875709532198

In [151]:
from sklearn.cluster import KMeans
kms = KMeans()
model = kms.fit_predict(x_train)

In [153]:
kms.labels_

array([1, 3, 6, ..., 4, 3, 5], shape=(15324,), dtype=int32)

In [157]:
from sklearn.decomposition import PCA

model = PCA(n_components=5)
xca = model.fit(x_train)
xca.explained_variance_ratio_

array([9.99523080e-01, 4.54626584e-04, 1.98255875e-05, 2.27320162e-06,
       1.84478366e-07])

In [159]:
model.transform(x_train)

array([[ 5.63726420e+04,  7.07568584e+03, -1.45044421e+01,
        -1.31112237e+02,  3.89448913e+01],
       [-3.34380036e+04,  2.37293262e+03,  1.17871769e+02,
        -1.68992924e+02, -2.36078207e+00],
       [-7.19392552e+04,  1.76783911e+03, -2.81670678e+01,
         3.74050485e+01,  1.12319409e+01],
       ...,
       [ 1.88959009e+05,  5.71671646e+02, -4.95299388e+01,
         3.59052114e+02, -1.04863460e+01],
       [-1.45436240e+04, -1.93977736e+02,  2.11260694e+02,
        -1.47897544e+02, -1.79039266e+01],
       [ 1.35856661e+05, -3.17843717e+02,  1.56661884e+02,
         2.31642014e+01,  1.13456940e+01]], shape=(15324, 5))

In [164]:
g = GridSearchCV(LogisticRegression(), {}, cv=5)
g.fit(x_train, y_train)

C:\Users\Vigna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Vigna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Vigna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Vigna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Vigna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Vigna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(cv=5, estimator=LogisticRegression(), param_grid={})

In [165]:
accuracy_score(y_test, g.predict(x_test))

0.5151693090624389